import { Modal } from '@mui/material';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.scss';
import connectMongoose from '../utils/connectMongo';
import AddNoteFab from './components/AddNoteFab';
import NotesWrapper from './components/NotesWrapper';
import TopBar from './components/TopBar';
import PopUpModal from './PopUpModal';
import Note from '../models/Note';

const Home = ({ pinnedNotes }) => {
  const [page, setPage] = useState(1);
  const [pageCount, setPageCount] = useState(0);
  const [editable, setEditable] = useState(false);

  // pop-up modal state
  const [open, setOpen] = useState(false);
  //used as handle for fab button
  const handleOpenNewNote = () => {
    setTitle('');
    setTagline('');
    setBody('');
    setPinned(false);
    setEditable(false);
    setOpen(true);
  };

  // handler when clicked on note
  const handleOpenNote = (note) => {
    setTitle(note.title);
    setTagline(note.tagline);
    setBody(note.body);
    setPinned(note.pinned);
    setEditable(true);
    setOpen(true);
  };

  const handleClose = () => setOpen(false);
  const [title, setTitle] = useState('');
  const [tagline, setTagline] = useState('');
  const [body, setBody] = useState('');
  const [pinned, setPinned] = useState(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <TopBar />
        <AddNoteFab createNote={handleOpenNewNote} />
        {JSON.parse(pinnedNotes) && JSON.parse(pinnedNotes).length > 0 && (
          <NotesWrapper
            title='Pinned Notes'
            notes={JSON.parse(pinnedNotes)}
            handleOpenNote={handleOpenNote}
          />
        )}
        <Modal open={open} onClose={handleClose}>
          <PopUpModal
            title={title}
            setTitle={setTitle}
            tagline={tagline}
            setTagline={setTagline}
            body={body}
            setBody={setBody}
            editable={editable}
          />
        </Modal>
      </main>
    </div>
  );
};

export async function getServerSideProps() {
  await connectMongoose();
  const pinnedNotes = await Note.find({ pinned: true });
  console.log(pinnedNotes);
  return {
    props: {
      pinnedNotes: JSON.stringify(pinnedNotes),
    },
  };
}

export default Home;
