import { Modal } from '@mui/material';
import Head from 'next/head';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.scss';
import AddNoteFab from './components/AddNoteFab';
import { Note } from './components/NoteCard';
import NotesWrapper from './components/NotesWrapper';
import TopBar from './components/TopBar';
import PopUpModal from './PopUpModal';

const Home = () => {
  const [pinnedNotes, setPinnedNotes] = useState([]);
  const [page, setPage] = useState(1);
  const [pageCount, setPageCount] = useState(0);
  const [editable, setEditable] = useState(false);

  // pop-up modal state
  const [open, setOpen] = useState(false);
  //used as handle for fab button
  const handleOpenNewNote = () => {
    setTitle('');
    setTagline('');
    setBody('');
    setPinned(false);
    setEditable(false);
    setOpen(true);
  };

  // handler when clicked on note
  const handleOpenNote = (note) => {
    setTitle(note.title);
    setTagline(note.tagline);
    setBody(note.body);
    setPinned(note.pinned);
    setEditable(true);
    setOpen(true);
  };

  const handleClose = () => setOpen(false);
  const [title, setTitle] = useState('');
  const [tagline, setTagline] = useState('');
  const [body, setBody] = useState('');
  const [pinned, setPinned] = useState(false);

  // initial fetching of pinned notes
  useEffect(() => {
    const fetchPinnedNotes = () => {
      fetch('/api/get-pinned-notes')
        .then((res) => res.json())
        .then((data) => setPinnedNotes(data.notes));
    };

    fetchPinnedNotes();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <TopBar />
        <AddNoteFab createNote={handleOpenNewNote} />
        {pinnedNotes && pinnedNotes.length > 0 && (
          <NotesWrapper
            title='Pinned Notes'
            notes={pinnedNotes}
            handleOpenNote={handleOpenNote}
          />
        )}
        <Modal open={open} onClose={handleClose}>
          <PopUpModal
            title={title}
            setTitle={setTitle}
            tagline={tagline}
            setTagline={setTagline}
            body={body}
            setBody={setBody}
            editable={editable}
          />
        </Modal>
      </main>
    </div>
  );
};

export default Home;
